### ISSUE TITLE
Unsupervised learning on pointclouds

### ISSUE THREAD

**Issue by Waleed15** [SimingYan/IAE#10]
I am trying to train an autoencoder on point clouds and use the features to classify them in different categories, I am confused in this case about which would be suitable for the encoder. I would be grateful if you could highlight which part of the code I should focus on.

**Comment by SimingYan** [comment]
Hi,
In our code, we use DGCNN as the encoder for feature extraction. Please refer to [src/encoder/dgcnn_cls.py](https://github.com/SimingYan/IAE/blob/8f5f68cd4c4ef7441d3080edb2dac001f5e4e2d9/src/encoder/dgcnn_cls.py) for the details of DGCNN encoder.
