### ISSUE TITLE
concerning to the effectiveness of pretrained model

### ISSUE THREAD

**Issue by Daniellli** [SimingYan/IAE#13]
Hi, 
i try to verify the performance of pretrained model in your codebase [DGCNN](https://github.com/SimingYan/dgcnn.pytorch).   The  results i get are listed as follows:
<img width="630" alt="Screenshot2022-12-20 10 25 07" src="https://user-images.githubusercontent.com/49134314/208567389-ff88c6d9-531f-4441-af3b-8fdab1b7f2af.png">

Here, no matter the pretrained model is loaded or not, I got the almost result. Is there any thing i do wrong?  

appreciate for your help.

**Comment by SimingYan** [comment]
I don't know what's going on here. I provided our training log [here](https://github.com/SimingYan/IAE/tree/main/downstream_tasks/segmentation) for your reference. Just following the instruction should be able to reproduce the result.

**Comment by SimingYan** [comment]
By the way, I noticed you opened many many issues here. Is that possible for you to merge all of them into one issue?
