### ISSUE TITLE
How to pretrain using PointNext backbone as encoder? 

### ISSUE THREAD

**Issue by Daniellli** [SimingYan/IAE#14]
hi, 
I am curious of how to pertrain with other backbone such   as PointNext.  And, as shown in  your paper, you experiment with PointNext and show a promising results.  Could you release the PointNext pretrain code.  

appreciate for your help.

**Comment by SimingYan** [comment]
We will public the new backbone model later. If you have read and understand our paper, you should find it is very easy to replace the encoder backbone. I would appreciate it a lot if you can also try to implement by yourself.
