### ISSUE TITLE
Linear evaluation on ModelNet40

### ISSUE THREAD

**Issue by Kracozebr** [SimingYan/IAE#16]
Hi, first of all thanks for sharing your code.

I'm trying to reproduce Linear evaluation on ModelNet40

I downloaded the dataset and run the evaluation:
```
python train_svm.py --encoder=dgcnn_cls --restore_path=./pretrained_models/modelnet40_svm.pt
```

And get the next result:
```
Transfer linear SVM accuracy: 92.06%
```

How to achieve the declared 94.2?

**Comment by SimingYan** [comment]
Hi,

The result of linear evaluation is 92.06%, which you have already achieved. And 94.2 is the fine-tuned classification result. This is different from linear evaluation.

**Comment by Kracozebr** [comment]
Ok, thanks for clarification.
