### ISSUE TITLE
trained ShapeNet decoder network for pretraining phase

### ISSUE THREAD

**Issue by JunseongAHN** [SimingYan/IAE#18]
Hello, thank you for your great job!

I am wondering if you can also release a decoder model that you trained with the ShapeNet dataset. I could find an encoder model $f$ for the pre-training stage, but a decoder model $g$.

By the way, I realized that you released a pre-trained model with a decoder under `downstream/segmentation`, which I failed to load with [dgcnn repo](https://github.com/SimingYan/dgcnn.pytorch).  Could you double-check?

Thank you!

**Comment by SimingYan** [comment]
Hi,

Thanks for your interest! I believe all the released pretrained models [here](https://github.com/SimingYan/IAE/tree/main/downstream_tasks/classification) should include the weight of decoder.

Could you please provide more information on the error messages for the failure cases?

**Comment by JunseongAHN** [comment]
Hello! Thank you for your fast reply!

You are right. I checked the shared weights again. It included the weight of the decoder, and I successfully loaded the released model for training!

Additionally, it was also my bad, I didn't use `copy_parameters(model, pretrained, verbose=True)` when loading the model haha...

Thank you so much for your help!:)
