### ISSUE TITLE
Evaluation code.

### ISSUE THREAD

**Issue by junshengzhou** [SimingYan/IAE#2]
Hi,
Thanks for your great job! I am confused with the below code in eval_step, where is the normailzed points and points_iou from?
```
        # add pre-computed index
        inputs = add_key(inputs, data.get('inputs.ind'), 'points', 'index', device=device)
        # add pre-computed normalized coordinates
        points = add_key(points, data.get('points.normalized'), 'p', 'p_n', device=device)
        points_iou = add_key(points_iou, data.get('points_iou.normalized'), 'p', 'p_n', device=device)
```
Thanks again!

**Comment by junshengzhou** [comment]
And by the way, could you please provide your pretrained model? I do marching cubes to my predicted sdf and find the results is poor after 600 epochs. I think it's abnormal.

**Comment by junshengzhou** [comment]
And by the way, could you please provide your pretrained model? I do marching cubes to my predicted sdf and find the results is poor after 100,000 iterations. I think it's abnormal.

**Comment by SimingYan** [comment]
Hi @junshengzhou ,

Thanks for your interest! I don't think we use 'points.normalized' term in eval_step. This line should be removed. Thanks for pointing this out. 
For 'points_iou', if you visualize it, you will find this is the dense version of 'points'. We use it to evaluate the IoU.

We have provided the model pretrained on scannet [here](https://github.com/SimingYan/IAE/tree/main/downstream_tasks/detection). 

If you do marching cubes and the result looks not good, you might need to adjust the threshold.

**Comment by junshengzhou** [comment]
Hi @SimingYan ,
Thanks for your quick reply! The 'point_iou' I asked means the 'points_iou.normalized'. According to my understanding, I need to delete all the there lines listed hear, right？
```
        inputs = add_key(inputs, data.get('inputs.ind'), 'points', 'index', device=device)
        points = add_key(points, data.get('points.normalized'), 'p', 'p_n', device=device)
        points_iou = add_key(points_iou, data.get('points_iou.normalized'), 'p', 'p_n', device=device)
```
And I am also confused by the threshold which is set to -0.1 when computing IoU.
```
        df_iou_np = (df_iou >= -0.1).cpu().numpy()
        df_iou_hat_np = (p_out >= -0.1).cpu().numpy()
```
I think it should be set to 0 when we use SDF as output(at least the threshold of ground truth SDF should be set to 0), or I may mistake someting?
And I am currently reproduction the experiments of ShapeNet, so could you kindly provide the pretrained model of ShapeNet? I have changed the threshold, and the results is still not good. And the IoU is only about 0.5 in the class airplane, but it's about 0.9 according to the results listed in ConvONet.
Thanks again for your great job!

**Comment by SimingYan** [comment]
Sorry for the late reply. I somehow missed this message...

--- I need to delete all the there lines listed hear, right？
--- Yes. I think so.

--- I think it should be set to 0 when we use SDF as output
--- I think this is also doable. 

--- the pretrained model of ShapeNet?
--- We have provided the pretrained model under `downstream_tasks/classification`. Please have a look. 

--- The IoU is only about 0.5 in the class airplane.
--- I don't really understand what's going on here. Could you please try to use occupancy value as the ground truth in our codebase and see if you can reproduce ConvOnet result?
