### ISSUE TITLE
ModuleNotFoundError: No module named 'vrcnet_util'

### ISSUE THREAD

**Issue by le-cheng** [SimingYan/IAE#4]
Can you reconfirm the code about (downstream_task / classification /)? In train_ svm. py, line 155. I don't know what 'vrcnet_util' is.thank you！
![image](https://user-images.githubusercontent.com/48431020/162965425-3954149a-f5a9-46cb-b3b2-f1612a19299a.png)

**Comment by SimingYan** [comment]
Hi @le-cheng ,

Thanks for pointing this out. I just updated the clean code. If you still have any questions, please let me know!
