### ISSUE TITLE
Completion results

### ISSUE THREAD

**Issue by ListIndexOutOfRange** [SimingYan/IAE#5]
Hi, thanks for your great work ! 

I don't quite understand how you obtain the completion results on ScanNet (Figure 4 of your article): as far as I understand, the model outputs implicit function values for ambiant points (that is, points uniformly sampled in the unit cube), so the output is simply one scalar values in [-1, 1] for each ambiant point. But it seems you obtain surfaces. Is that correct ? And if so, how is that done ?

**Comment by SimingYan** [comment]
Hi @ListIndexOutOfRange,

We used the marching cubes algorithm to extract the mesh completion results. There are many good implementations and I recommand the [convolutional occupancy network repo](https://github.com/autonomousvision/convolutional_occupancy_networks/blob/f44d413f8d455657a44c24d06163934c69141a09/src/conv_onet/generation.py) for your reference.
