### ISSUE TITLE
Reproduce the results on ModelNet40 dataset

### ISSUE THREAD

**Issue by YBZh** [SimingYan/IAE#8]
Hi, thanks for your contribution. I am trying to reproduce your fine-tuning results on ModelNet40. I follow your suggestion to prepare the ModelNet40 dataset, download your pre-trained models, and use your suggested command for fine-tuning.  I conduct the experiments twice. As for the results, one is 93.1 and another is 93.0, which is different from your reported 94.2.

I carefully compare your released log with 94.2 ACC and my log. I find some differences. 
1. In your log, the model is fine-tuned for 250 epochs, while in the released code, the epoch is set as 200.
2. In your log, batch size is set as 32, while in the released code, the epoch is set as 24.
3. In your log, num_point is set as 2048 and k is set as 40, while in the released code, the number point is set as 1024 and k is set as 20. 

I am wondering which difference plays such an important role in the ModelNet40 evaluation. Could you give me some suggestions?  Thanks for your time.

**Comment by SimingYan** [comment]
Hi @YBZh ,

Thanks for pointing this out! I will update the default setting soon. 
Your observation is very good! According to my experience, 3rd point is the most important difference. 1 and 2 should not influence too much. Please set num_point to 2048 and k=40 and try again. If you still cannot reproduce the close result, please let me know.
